# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

"""
Auto-generated class for aci
"""
from six import string_types

from . import client_support


class aci(object):
    """
    auto-generated. don't touch.
    """

    @staticmethod
    def create(**kwargs):
        """
        :type groups: int
        :type hash: string_types
        :type right: string_types
        :type uid: int
        :type users: int
        :rtype: aci
        """

        return aci(**kwargs)

    def __init__(self, json=None, **kwargs):
        if json is None and not kwargs:
            raise ValueError('No data or kwargs present')

        class_name = 'aci'
        data = json or kwargs

        # set attributes
        data_types = [int]
        self.groups = client_support.set_property('groups', data, data_types, False, [], False, False, class_name)
        data_types = [string_types]
        self.hash = client_support.set_property('hash', data, data_types, False, [], False, True, class_name)
        data_types = [string_types]
        self.right = client_support.set_property('right', data, data_types, False, [], False, True, class_name)
        data_types = [int]
        self.uid = client_support.set_property('uid', data, data_types, False, [], False, True, class_name)
        data_types = [int]
        self.users = client_support.set_property('users', data, data_types, False, [], False, False, class_name)

    def __str__(self):
        return self.as_json(indent=4)

    def as_json(self, indent=0):
        return client_support.to_json(self, indent=indent)

    def as_dict(self):
        return client_support.to_dict(self)
