# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

from enum import Enum


class EnumSpecialType(Enum):
    socket = "socket"
    block = "block"
    char = "char"
    fifo = "fifo"
