# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

"""
Auto-generated class for file
"""
from six import string_types

from . import client_support


class file(object):
    """
    auto-generated. don't touch.
    """

    @staticmethod
    def create(**kwargs):
        """
        :type blockSize: int
        :type blocks: string_types
        :type moddate: int
        :type name: string_types
        :type posix: string_types
        :type size: int
        :rtype: file
        """

        return file(**kwargs)

    def __init__(self, json=None, **kwargs):
        if json is None and not kwargs:
            raise ValueError('No data or kwargs present')

        class_name = 'file'
        data = json or kwargs

        # set attributes
        data_types = [int]
        self.blockSize = client_support.set_property('blockSize', data, data_types, False, [], False, True, class_name)
        data_types = [string_types]
        self.blocks = client_support.set_property('blocks', data, data_types, False, [], False, True, class_name)
        data_types = [int]
        self.moddate = client_support.set_property('moddate', data, data_types, False, [], False, True, class_name)
        data_types = [string_types]
        self.name = client_support.set_property('name', data, data_types, False, [], False, True, class_name)
        data_types = [string_types]
        self.posix = client_support.set_property('posix', data, data_types, False, [], False, False, class_name)
        data_types = [int]
        self.size = client_support.set_property('size', data, data_types, False, [], False, True, class_name)

    def __str__(self):
        return self.as_json(indent=4)

    def as_json(self, indent=0):
        return client_support.to_json(self, indent=indent)

    def as_dict(self):
        return client_support.to_dict(self)
