# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

"""
Auto-generated class for fileblock
"""
from six import string_types

from . import client_support


class fileblock(object):
    """
    auto-generated. don't touch.
    """

    @staticmethod
    def create(**kwargs):
        """
        :type hash: string_types
        :type key: string_types
        :type zstormetadata: string_types
        :rtype: fileblock
        """

        return fileblock(**kwargs)

    def __init__(self, json=None, **kwargs):
        if json is None and not kwargs:
            raise ValueError('No data or kwargs present')

        class_name = 'fileblock'
        data = json or kwargs

        # set attributes
        data_types = [string_types]
        self.hash = client_support.set_property('hash', data, data_types, False, [], False, False, class_name)
        data_types = [string_types]
        self.key = client_support.set_property('key', data, data_types, False, [], False, False, class_name)
        data_types = [string_types]
        self.zstormetadata = client_support.set_property(
            'zstormetadata', data, data_types, False, [], False, False, class_name)

    def __str__(self):
        return self.as_json(indent=4)

    def as_json(self, indent=0):
        return client_support.to_json(self, indent=indent)

    def as_dict(self):
        return client_support.to_dict(self)
