# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

"""
Auto-generated class for link_bobject
"""
from six import string_types

from . import client_support


class link_bobject(object):
    """
    auto-generated. don't touch.
    """

    @staticmethod
    def create(**kwargs):
        """
        :type bdomain: int
        :type buid: int
        :type moddate: int
        :type name: string_types
        :type secret: string_types
        :rtype: link_bobject
        """

        return link_bobject(**kwargs)

    def __init__(self, json=None, **kwargs):
        if json is None and not kwargs:
            raise ValueError('No data or kwargs present')

        class_name = 'link_bobject'
        data = json or kwargs

        # set attributes
        data_types = [int]
        self.bdomain = client_support.set_property('bdomain', data, data_types, False, [], False, True, class_name)
        data_types = [int]
        self.buid = client_support.set_property('buid', data, data_types, False, [], False, True, class_name)
        data_types = [int]
        self.moddate = client_support.set_property('moddate', data, data_types, False, [], False, True, class_name)
        data_types = [string_types]
        self.name = client_support.set_property('name', data, data_types, False, [], False, True, class_name)
        data_types = [string_types]
        self.secret = client_support.set_property('secret', data, data_types, False, [], False, False, class_name)

    def __str__(self):
        return self.as_json(indent=4)

    def as_json(self, indent=0):
        return client_support.to_json(self, indent=indent)

    def as_dict(self):
        return client_support.to_dict(self)
