# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

"""
Auto-generated class for posix
"""
from six import string_types

from . import client_support


class posix(object):
    """
    auto-generated. don't touch.
    """

    @staticmethod
    def create(**kwargs):
        """
        :type gname: string_types
        :type mode: int
        :type uname: string_types
        :rtype: posix
        """

        return posix(**kwargs)

    def __init__(self, json=None, **kwargs):
        if json is None and not kwargs:
            raise ValueError('No data or kwargs present')

        class_name = 'posix'
        data = json or kwargs

        # set attributes
        data_types = [string_types]
        self.gname = client_support.set_property('gname', data, data_types, False, [], False, True, class_name)
        data_types = [int]
        self.mode = client_support.set_property('mode', data, data_types, False, [], False, False, class_name)
        data_types = [string_types]
        self.uname = client_support.set_property('uname', data, data_types, False, [], False, True, class_name)

    def __str__(self):
        return self.as_json(indent=4)

    def as_json(self, indent=0):
        return client_support.to_json(self, indent=indent)

    def as_dict(self):
        return client_support.to_dict(self)
