# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

"""
Auto-generated class for special
"""
from .EnumSpecialType import EnumSpecialType
from six import string_types

from . import client_support


class special(object):
    """
    auto-generated. don't touch.
    """

    @staticmethod
    def create(**kwargs):
        """
        :type data: string_types
        :type moddate: int
        :type name: string_types
        :type type: EnumSpecialType
        :rtype: special
        """

        return special(**kwargs)

    def __init__(self, json=None, **kwargs):
        if json is None and not kwargs:
            raise ValueError('No data or kwargs present')

        class_name = 'special'
        data = json or kwargs

        # set attributes
        data_types = [string_types]
        self.data = client_support.set_property('data', data, data_types, False, [], False, False, class_name)
        data_types = [int]
        self.moddate = client_support.set_property('moddate', data, data_types, False, [], False, True, class_name)
        data_types = [string_types]
        self.name = client_support.set_property('name', data, data_types, False, [], False, True, class_name)
        data_types = [EnumSpecialType]
        self.type = client_support.set_property('type', data, data_types, False, [], False, True, class_name)

    def __str__(self):
        return self.as_json(indent=4)

    def as_json(self, indent=0):
        return client_support.to_json(self, indent=indent)

    def as_dict(self):
        return client_support.to_dict(self)
