# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

from .EnumBobjectCompressionType import EnumBobjectCompressionType
from .EnumLinkType import EnumLinkType
from .EnumSpecialType import EnumSpecialType
from .aci import aci
from .acl import acl
from .bdomain import bdomain
from .bobject import bobject
from .dir import dir
from .file import file
from .fileblock import fileblock
from .group import group
from .link import link
from .link_bobject import link_bobject
from .metadata import metadata
from .posix import posix
from .special import special
from .user import user

from .acl_service import AclService
from .bdomain_service import BdomainService
from .bobject_service import BobjectService
from .dir_service import DirService
from .group_service import GroupService
from .user_service import UserService

from .http_client import HTTPClient


class Client:
    def __init__(self, base_uri="http://127.0.0.1:5000/"):
        http_client = HTTPClient(base_uri)
        self.acl = AclService(http_client)
        self.bdomain = BdomainService(http_client)
        self.bobject = BobjectService(http_client)
        self.dir = DirService(http_client)
        self.group = GroupService(http_client)
        self.user = UserService(http_client)
        self.close = http_client.close
