# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.


class AclService:
    def __init__(self, client):
        self.client = client

    def deleteAcl(self, id, headers=None, query_params=None, content_type="application/json"):
        """
        Delete acl
        It is method for DELETE /acl/{id}
        """
        uri = self.client.base_url + "/acl/" + id
        return self.client.delete(uri, None, headers, query_params, content_type)

    def getAcl(self, id, headers=None, query_params=None, content_type="application/json"):
        """
        Get acl, id=int
        It is method for GET /acl/{id}
        """
        uri = self.client.base_url + "/acl/" + id
        return self.client.get(uri, None, headers, query_params, content_type)

    def updateAcl(self, data, id, headers=None, query_params=None, content_type="application/json"):
        """
        Update acl
        It is method for POST /acl/{id}
        """
        uri = self.client.base_url + "/acl/" + id
        return self.client.post(uri, data, headers, query_params, content_type)

    def listAcl(self, headers=None, query_params=None, content_type="application/json"):
        """
        Get a list of acls
        It is method for GET /acl
        """
        uri = self.client.base_url + "/acl"
        return self.client.get(uri, None, headers, query_params, content_type)
