# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
from .acl import acl
from .unhandled_api_error import UnhandledAPIError
from .unmarshall_error import UnmarshallError


class AclService:
    def __init__(self, client):
        self.client = client

    def deleteAcl(self, id, headers=None, query_params=None, content_type="application/json"):
        """
        Delete acl
        It is method for DELETE /acl/{id}
        """
        uri = self.client.base_url + "/acl/" + id
        resp = self.client.delete(uri, None, headers, query_params, content_type)
        try:
            if resp.status_code == 200:
                return acl(resp.json()), resp

            message = 'unknown status code={}'.format(resp.status_code)
            raise UnhandledAPIError(response=resp, code=resp.status_code,
                                    message=message)
        except ValueError as msg:
            raise UnmarshallError(resp, msg)
        except UnhandledAPIError as uae:
            raise uae
        except Exception as e:
            raise UnmarshallError(resp, e.message)

    def getAcl(self, id, headers=None, query_params=None, content_type="application/json"):
        """
        Get acl, id=int
        It is method for GET /acl/{id}
        """
        uri = self.client.base_url + "/acl/" + id
        resp = self.client.get(uri, None, headers, query_params, content_type)
        try:
            if resp.status_code == 200:
                return acl(resp.json()), resp

            message = 'unknown status code={}'.format(resp.status_code)
            raise UnhandledAPIError(response=resp, code=resp.status_code,
                                    message=message)
        except ValueError as msg:
            raise UnmarshallError(resp, msg)
        except UnhandledAPIError as uae:
            raise uae
        except Exception as e:
            raise UnmarshallError(resp, e.message)

    def updateAcl(self, data, id, headers=None, query_params=None, content_type="application/json"):
        """
        Update acl
        It is method for POST /acl/{id}
        """
        uri = self.client.base_url + "/acl/" + id
        resp = self.client.post(uri, data, headers, query_params, content_type)
        try:
            if resp.status_code == 200:
                return acl(resp.json()), resp

            message = 'unknown status code={}'.format(resp.status_code)
            raise UnhandledAPIError(response=resp, code=resp.status_code,
                                    message=message)
        except ValueError as msg:
            raise UnmarshallError(resp, msg)
        except UnhandledAPIError as uae:
            raise uae
        except Exception as e:
            raise UnmarshallError(resp, e.message)

    def listAcl(self, headers=None, query_params=None, content_type="application/json"):
        """
        Get a list of acls
        It is method for GET /acl
        """
        uri = self.client.base_url + "/acl"
        resp = self.client.get(uri, None, headers, query_params, content_type)
        try:
            if resp.status_code == 200:
                resps = []
                for elem in resp.json():
                    resps.append(acl(elem))
                return resps, resp

            message = 'unknown status code={}'.format(resp.status_code)
            raise UnhandledAPIError(response=resp, code=resp.status_code,
                                    message=message)
        except ValueError as msg:
            raise UnmarshallError(resp, msg)
        except UnhandledAPIError as uae:
            raise uae
        except Exception as e:
            raise UnmarshallError(resp, e.message)
