# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
from .bdomain import bdomain
from .unhandled_api_error import UnhandledAPIError
from .unmarshall_error import UnmarshallError


class BdomainService:
    def __init__(self, client):
        self.client = client

    def deleteBdomain(self, id, headers=None, query_params=None, content_type="application/json"):
        """
        Delete bdomain
        It is method for DELETE /bdomain/{id}
        """
        uri = self.client.base_url + "/bdomain/" + id
        resp = self.client.delete(uri, None, headers, query_params, content_type)
        try:
            if resp.status_code == 200:
                return bdomain(resp.json()), resp

            message = 'unknown status code={}'.format(resp.status_code)
            raise UnhandledAPIError(response=resp, code=resp.status_code,
                                    message=message)
        except ValueError as msg:
            raise UnmarshallError(resp, msg)
        except UnhandledAPIError as uae:
            raise uae
        except Exception as e:
            raise UnmarshallError(resp, e.message)

    def getBdomain(self, id, headers=None, query_params=None, content_type="application/json"):
        """
        Get bdomain, id=int
        It is method for GET /bdomain/{id}
        """
        uri = self.client.base_url + "/bdomain/" + id
        resp = self.client.get(uri, None, headers, query_params, content_type)
        try:
            if resp.status_code == 200:
                return bdomain(resp.json()), resp

            message = 'unknown status code={}'.format(resp.status_code)
            raise UnhandledAPIError(response=resp, code=resp.status_code,
                                    message=message)
        except ValueError as msg:
            raise UnmarshallError(resp, msg)
        except UnhandledAPIError as uae:
            raise uae
        except Exception as e:
            raise UnmarshallError(resp, e.message)

    def updateBdomain(self, data, id, headers=None, query_params=None, content_type="application/json"):
        """
        Update bdomain
        It is method for POST /bdomain/{id}
        """
        uri = self.client.base_url + "/bdomain/" + id
        resp = self.client.post(uri, data, headers, query_params, content_type)
        try:
            if resp.status_code == 200:
                return bdomain(resp.json()), resp

            message = 'unknown status code={}'.format(resp.status_code)
            raise UnhandledAPIError(response=resp, code=resp.status_code,
                                    message=message)
        except ValueError as msg:
            raise UnmarshallError(resp, msg)
        except UnhandledAPIError as uae:
            raise uae
        except Exception as e:
            raise UnmarshallError(resp, e.message)

    def listBdomain(self, headers=None, query_params=None, content_type="application/json"):
        """
        Get a list of bdomains
        It is method for GET /bdomain
        """
        uri = self.client.base_url + "/bdomain"
        resp = self.client.get(uri, None, headers, query_params, content_type)
        try:
            if resp.status_code == 200:
                resps = []
                for elem in resp.json():
                    resps.append(bdomain(elem))
                return resps, resp

            message = 'unknown status code={}'.format(resp.status_code)
            raise UnhandledAPIError(response=resp, code=resp.status_code,
                                    message=message)
        except ValueError as msg:
            raise UnmarshallError(resp, msg)
        except UnhandledAPIError as uae:
            raise uae
        except Exception as e:
            raise UnmarshallError(resp, e.message)
