# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.


class BdomainService:
    def __init__(self, client):
        self.client = client

    def deleteBdomain(self, id, headers=None, query_params=None, content_type="application/json"):
        """
        Delete bdomain
        It is method for DELETE /bdomain/{id}
        """
        uri = self.client.base_url + "/bdomain/" + id
        return self.client.delete(uri, None, headers, query_params, content_type)

    def getBdomain(self, id, headers=None, query_params=None, content_type="application/json"):
        """
        Get bdomain, id=int
        It is method for GET /bdomain/{id}
        """
        uri = self.client.base_url + "/bdomain/" + id
        return self.client.get(uri, None, headers, query_params, content_type)

    def updateBdomain(self, data, id, headers=None, query_params=None, content_type="application/json"):
        """
        Update bdomain
        It is method for POST /bdomain/{id}
        """
        uri = self.client.base_url + "/bdomain/" + id
        return self.client.post(uri, data, headers, query_params, content_type)

    def listBdomain(self, headers=None, query_params=None, content_type="application/json"):
        """
        Get a list of bdomains
        It is method for GET /bdomain
        """
        uri = self.client.base_url + "/bdomain"
        return self.client.get(uri, None, headers, query_params, content_type)
