# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
from .bobject import bobject
from .unhandled_api_error import UnhandledAPIError
from .unmarshall_error import UnmarshallError


class BobjectService:
    def __init__(self, client):
        self.client = client

    def deleteBobject(self, id, headers=None, query_params=None, content_type="application/json"):
        """
        Delete bobject
        It is method for DELETE /bobject/{id}
        """
        uri = self.client.base_url + "/bobject/" + id
        return self.client.delete(uri, None, headers, query_params, content_type)

    def getBobject(self, id, headers=None, query_params=None, content_type="application/json"):
        """
        Get bobject, id=int
        It is method for GET /bobject/{id}
        """
        uri = self.client.base_url + "/bobject/" + id
        resp = self.client.get(uri, None, headers, query_params, content_type)
        try:
            if resp.status_code == 200:
                return bobject(resp.json()), resp

            message = 'unknown status code={}'.format(resp.status_code)
            raise UnhandledAPIError(response=resp, code=resp.status_code,
                                    message=message)
        except ValueError as msg:
            raise UnmarshallError(resp, msg)
        except UnhandledAPIError as uae:
            raise uae
        except Exception as e:
            raise UnmarshallError(resp, e.message)

    def updateBobject(self, data, id, headers=None, query_params=None, content_type="application/json"):
        """
        Update bobject
        It is method for POST /bobject/{id}
        """
        uri = self.client.base_url + "/bobject/" + id
        resp = self.client.post(uri, data, headers, query_params, content_type)
        try:
            if resp.status_code == 200:
                return bobject(resp.json()), resp

            message = 'unknown status code={}'.format(resp.status_code)
            raise UnhandledAPIError(response=resp, code=resp.status_code,
                                    message=message)
        except ValueError as msg:
            raise UnmarshallError(resp, msg)
        except UnhandledAPIError as uae:
            raise uae
        except Exception as e:
            raise UnmarshallError(resp, e.message)

    def listBobject(self, headers=None, query_params=None, content_type="application/json"):
        """
        Get a list of bobjects
        It is method for GET /bobject
        """
        uri = self.client.base_url + "/bobject"
        resp = self.client.get(uri, None, headers, query_params, content_type)
        try:
            if resp.status_code == 200:
                resps = []
                for elem in resp.json():
                    resps.append(bobject(elem))
                return resps, resp

            message = 'unknown status code={}'.format(resp.status_code)
            raise UnhandledAPIError(response=resp, code=resp.status_code,
                                    message=message)
        except ValueError as msg:
            raise UnmarshallError(resp, msg)
        except UnhandledAPIError as uae:
            raise uae
        except Exception as e:
            raise UnmarshallError(resp, e.message)
