# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.


class BobjectService:
    def __init__(self, client):
        self.client = client

    def deleteBobject(self, id, headers=None, query_params=None, content_type="application/json"):
        """
        Delete bobject
        It is method for DELETE /bobject/{id}
        """
        uri = self.client.base_url + "/bobject/" + id
        return self.client.delete(uri, None, headers, query_params, content_type)

    def getBobject(self, id, headers=None, query_params=None, content_type="application/json"):
        """
        Get bobject, id=int
        It is method for GET /bobject/{id}
        """
        uri = self.client.base_url + "/bobject/" + id
        return self.client.get(uri, None, headers, query_params, content_type)

    def updateBobject(self, data, id, headers=None, query_params=None, content_type="application/json"):
        """
        Update bobject
        It is method for POST /bobject/{id}
        """
        uri = self.client.base_url + "/bobject/" + id
        return self.client.post(uri, data, headers, query_params, content_type)

    def listBobject(self, headers=None, query_params=None, content_type="application/json"):
        """
        Get a list of bobjects
        It is method for GET /bobject
        """
        uri = self.client.base_url + "/bobject"
        return self.client.get(uri, None, headers, query_params, content_type)
