# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
from .dir import dir
from .unhandled_api_error import UnhandledAPIError
from .unmarshall_error import UnmarshallError


class DirService:
    def __init__(self, client):
        self.client = client

    def deleteDir(self, id, headers=None, query_params=None, content_type="application/json"):
        """
        Delete dir
        It is method for DELETE /dir/{id}
        """
        uri = self.client.base_url + "/dir/" + id
        return self.client.delete(uri, None, headers, query_params, content_type)

    def getDir(self, id, headers=None, query_params=None, content_type="application/json"):
        """
        Get dir, id=int
        It is method for GET /dir/{id}
        """
        uri = self.client.base_url + "/dir/" + id
        resp = self.client.get(uri, None, headers, query_params, content_type)
        try:
            if resp.status_code == 200:
                return dir(resp.json()), resp

            message = 'unknown status code={}'.format(resp.status_code)
            raise UnhandledAPIError(response=resp, code=resp.status_code,
                                    message=message)
        except ValueError as msg:
            raise UnmarshallError(resp, msg)
        except UnhandledAPIError as uae:
            raise uae
        except Exception as e:
            raise UnmarshallError(resp, e.message)

    def updateDir(self, data, id, headers=None, query_params=None, content_type="application/json"):
        """
        Update dir
        It is method for POST /dir/{id}
        """
        uri = self.client.base_url + "/dir/" + id
        resp = self.client.post(uri, data, headers, query_params, content_type)
        try:
            if resp.status_code == 200:
                return dir(resp.json()), resp

            message = 'unknown status code={}'.format(resp.status_code)
            raise UnhandledAPIError(response=resp, code=resp.status_code,
                                    message=message)
        except ValueError as msg:
            raise UnmarshallError(resp, msg)
        except UnhandledAPIError as uae:
            raise uae
        except Exception as e:
            raise UnmarshallError(resp, e.message)

    def listDir(self, headers=None, query_params=None, content_type="application/json"):
        """
        Get a list of dirs
        It is method for GET /dir
        """
        uri = self.client.base_url + "/dir"
        resp = self.client.get(uri, None, headers, query_params, content_type)
        try:
            if resp.status_code == 200:
                resps = []
                for elem in resp.json():
                    resps.append(dir(elem))
                return resps, resp

            message = 'unknown status code={}'.format(resp.status_code)
            raise UnhandledAPIError(response=resp, code=resp.status_code,
                                    message=message)
        except ValueError as msg:
            raise UnmarshallError(resp, msg)
        except UnhandledAPIError as uae:
            raise uae
        except Exception as e:
            raise UnmarshallError(resp, e.message)
