# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.


class DirService:
    def __init__(self, client):
        self.client = client

    def deleteDir(self, id, headers=None, query_params=None, content_type="application/json"):
        """
        Delete dir
        It is method for DELETE /dir/{id}
        """
        uri = self.client.base_url + "/dir/" + id
        return self.client.delete(uri, None, headers, query_params, content_type)

    def getDir(self, id, headers=None, query_params=None, content_type="application/json"):
        """
        Get dir, id=int
        It is method for GET /dir/{id}
        """
        uri = self.client.base_url + "/dir/" + id
        return self.client.get(uri, None, headers, query_params, content_type)

    def updateDir(self, data, id, headers=None, query_params=None, content_type="application/json"):
        """
        Update dir
        It is method for POST /dir/{id}
        """
        uri = self.client.base_url + "/dir/" + id
        return self.client.post(uri, data, headers, query_params, content_type)

    def listDir(self, headers=None, query_params=None, content_type="application/json"):
        """
        Get a list of dirs
        It is method for GET /dir
        """
        uri = self.client.base_url + "/dir"
        return self.client.get(uri, None, headers, query_params, content_type)
