# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

from enum import Enum


class EnumBobjectCompressionType(Enum):
    none = "none"
    blosc = "blosc"
    snappy = "snappy"
