# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.


class GroupService:
    def __init__(self, client):
        self.client = client

    def deleteGroup(self, id, headers=None, query_params=None, content_type="application/json"):
        """
        Delete group
        It is method for DELETE /group/{id}
        """
        uri = self.client.base_url + "/group/" + id
        return self.client.delete(uri, None, headers, query_params, content_type)

    def getGroup(self, id, headers=None, query_params=None, content_type="application/json"):
        """
        Get group, id=int
        It is method for GET /group/{id}
        """
        uri = self.client.base_url + "/group/" + id
        return self.client.get(uri, None, headers, query_params, content_type)

    def updateGroup(self, data, id, headers=None, query_params=None, content_type="application/json"):
        """
        Update group
        It is method for POST /group/{id}
        """
        uri = self.client.base_url + "/group/" + id
        return self.client.post(uri, data, headers, query_params, content_type)

    def listGroup(self, headers=None, query_params=None, content_type="application/json"):
        """
        Get a list of groups
        It is method for GET /group
        """
        uri = self.client.base_url + "/group"
        return self.client.get(uri, None, headers, query_params, content_type)
