# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
from .unhandled_api_error import UnhandledAPIError
from .unmarshall_error import UnmarshallError
from .user import user


class UserService:
    def __init__(self, client):
        self.client = client

    def deleteUser(self, id, headers=None, query_params=None, content_type="application/json"):
        """
        Delete user
        It is method for DELETE /user/{id}
        """
        uri = self.client.base_url + "/user/" + id
        resp = self.client.delete(uri, None, headers, query_params, content_type)
        try:
            if resp.status_code == 200:
                return user(resp.json()), resp 
                # return None, resp  # Must be none as a delete should not return any record
        
            message = 'unknown status code={}'.format(resp.status_code)
            raise UnhandledAPIError(response=resp, code=resp.status_code,
                                    message=message)
        except ValueError as msg:
            raise UnmarshallError(resp, msg)
        except UnhandledAPIError as uae:
            raise uae
        except Exception as e:
            raise UnmarshallError(resp, e.message)

    def getUser(self, id, headers=None, query_params=None, content_type="application/json"):
        """
        Get user, id=int
        It is method for GET /user/{id}
        """
        uri = self.client.base_url + "/user/" + id
        resp = self.client.get(uri, None, headers, query_params, content_type)
        try:
            if resp.status_code == 200:
                return user(resp.json()), resp

            message = 'unknown status code={}'.format(resp.status_code)
            raise UnhandledAPIError(response=resp, code=resp.status_code,
                                    message=message)
        except ValueError as msg:
            raise UnmarshallError(resp, msg)
        except UnhandledAPIError as uae:
            raise uae
        except Exception as e:
            raise UnmarshallError(resp, e.message)

    def updateUser(self, data, id, headers=None, query_params=None, content_type="application/json"):
        """
        Update user
        It is method for POST /user/{id}
        """
        uri = self.client.base_url + "/user/" + id
        resp = self.client.post(uri, data, headers, query_params, content_type)
        try:
            if resp.status_code == 200:
                return user(resp.json()), resp

            message = 'unknown status code={}'.format(resp.status_code)
            raise UnhandledAPIError(response=resp, code=resp.status_code,
                                    message=message)
        except ValueError as msg:
            raise UnmarshallError(resp, msg)
        except UnhandledAPIError as uae:
            raise uae
        except Exception as e:
            raise UnmarshallError(resp, e.message)

    def listUser(self, headers=None, query_params=None, content_type="application/json"):
        """
        Get a list of users
        It is method for GET /user
        """
        uri = self.client.base_url + "/user"
        resp = self.client.get(uri, None, headers, query_params, content_type)
        try:
            if resp.status_code == 200:
                resps = []
                for elem in resp.json():
                    resps.append(user(elem))
                return resps, resp

            message = 'unknown status code={}'.format(resp.status_code)
            raise UnhandledAPIError(response=resp, code=resp.status_code,
                                    message=message)
        except ValueError as msg:
            raise UnmarshallError(resp, msg)
        except UnhandledAPIError as uae:
            raise uae
        except Exception as e:
            raise UnmarshallError(resp, e.message)
