# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.


class UserService:
    def __init__(self, client):
        self.client = client

    def deleteUser(self, id, headers=None, query_params=None, content_type="application/json"):
        """
        Delete user
        It is method for DELETE /user/{id}
        """
        uri = self.client.base_url + "/user/" + id
        return self.client.delete(uri, None, headers, query_params, content_type)

    def getUser(self, id, headers=None, query_params=None, content_type="application/json"):
        """
        Get user, id=int
        It is method for GET /user/{id}
        """
        uri = self.client.base_url + "/user/" + id
        return self.client.get(uri, None, headers, query_params, content_type)

    def updateUser(self, data, id, headers=None, query_params=None, content_type="application/json"):
        """
        Update user
        It is method for POST /user/{id}
        """
        uri = self.client.base_url + "/user/" + id
        return self.client.post(uri, data, headers, query_params, content_type)

    def listUser(self, headers=None, query_params=None, content_type="application/json"):
        """
        Get a list of users
        It is method for GET /user
        """
        uri = self.client.base_url + "/user"
        return self.client.get(uri, None, headers, query_params, content_type)
