# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
using import "Aci.capnp".Aci;
@0x877ec031ab4892d4;

struct Acl {
  aci @0 :List(Aci);
  hash @1 :Text;
  uid @2 :Int32;
}
