# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
@0x9fef62bec082685f;

struct Bdomain {
  addr @0 :Text;
  admins @1 :Int32;
  author @2 :UInt32;
  description @3 :Text;
  id @4 :UInt32;
  moddate @5 :UInt32;
  name @6 :Text;
  signature @7 :Text;
  uid @8 :UInt32;
}
