# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
using import "EnumBobjectCompressionType.capnp".EnumBobjectCompressionType;
@0xbe9701a374696d34;

struct Bobject {
  author @0 :UInt32;
  compressionType @1 :EnumBobjectCompressionType;
  data @2 :Text;
  digitalmeUrl @3:Text;
  domain @4 :UInt32;
  id @5 :UInt32;
  key @6 :Text;
  moddate @7 :UInt32;
  signature @8 :Text;
  uid @9 :UInt32;
}
