# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
@0xff7692564e2ecbb6;

struct File {
  blockSize @0 :UInt16;
  blocks @1 :Text;
  moddate @2 :UInt32;
  name @3 :Text;
  posix @4 :Text;
  size @5 :UInt32;
}
