# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
@0xaad30d14dded5c03;

struct Group {
  addr @0 :Text;
  alias @1 :List(Text);
  keyPub @2 :List(Text);
  owners @3 :Int32;
  uid @4 :Int32;
}
