# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
using import "EnumSpecialType.capnp".EnumSpecialType;
@0xdc619e310cd522f0;

struct Special {
  data @0 :Text;
  moddate @1 :UInt32;
  name @2 :Text;
  type @3 :EnumSpecialType;
}
