# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
@0xa31b2e0656da3be6;

struct User {
  addr @0 :Text;
  alias @1 :List(Text);
  keyPub @2 :List(Text);
  uid @3 :Int32;
}
