#!/usr/bin/python3
from metadatastor import Client, CreateDirectory
from datetime import datetime

client = Client(base_uri="https://metadata01.foo.bar")

# Listing files and directories in root
for entry in client.tree.get(path="/"):
    print("%s (%s)" % (entry.name, entry.type))

# Download file /etc/hosts, and print it
print(client.tree.get(path="/etc/hosts").decode("utf8"))

# Show last modification time of /etc/hosts file
print(datetime.fromtimestamp(client.tree.get(path="/etc/hosts", inspect=True).modified))

# Display full tree
def print_node(node, indent):
    print("%s%s" % (indent, node.name))
    for child in node.children:
        print_node(child, "%s  |-" % indent)
for entry in client.tree.get(path="/", depth=-1):
    print_node(entry, "|-")

# Create file /tmp/hello
client.tree.create(path="/tmp/hello", data="""world""".encode("utf8"), content_type="binary/octet_stream")

# Create directory /tmp/test
newdir = CreateDirectory()
newdir.name = "test"
client.tree.create(path="/tmp", data=newdir.as_json())

# Update hosts file
client.tree.update(path="/etc/hosts", data="""# This file is automatically generated by WSL based on the Windows hosts file:
# %WINDIR%\System32\drivers\etc\hosts. Modifications to this file will be overwritten.
127.0.0.1       localhost
127.0.1.1       DESKTOP-PRP34CJ.localdomain     DESKTOP-PRP34CJ
127.0.0.1       localhost       htmlpreviewer.github.moehaha
::1     localhost
192.168.16.152  rt.dev

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters""".encode("utf8"))

# Delete file /tmp/hello
client.tree.delete(path="/tmp/hello")

# Delete directory /tmp/test
client.tree.delete(path="/tmp/hello")

# Delete directory /etc and all children
client.tree.delete(path="/etc", recursive=True)