#%RAML 1.0 traits

stdresponse:
  responses:
    '200':
      body:
        application/json:
          type: <<resourcePathName | !singularize>>
    '404':
      body:
        text/html:
          type: string

stdpostresponse:
  responses:
    '200':
      body:
        application/json:
          type: <<resourcePathName | !singularize>>
    '400':
      description: Bad Request
    '403':
      description: ID already exists, could not create
      body:
        text/html:
          type: string

stddelresponse:
  responses:
    '204':
      description: <<resourcePathName | !singularize | !uppercamelcase >> deleted
    '404':
      description: <<resourcePathName | !singularize | !uppercamelcase >> not found
      body:
        text/html:
          type: string

stdresponsetype:
  responses:
    '200':
      body:
        application/json:
          type: <<ttype>>

authfailure:
  responses:
    '403':
      body:
        text/plain:
          type: string
      description: Authentication failure or  <<resourcePathName | !singularize | !lowercase >> not viewable

listresponse:
    displayName:  list<<resourcePathName | !pluralize  | !uppercamelcase >>
    description: Get a list of <<resourcePathName | !pluralize  | !lowercase >>
    responses:
      '200':
        body:
          application/json:
            type: <<resourcePathName | !singularize>>[]
        description: Array of <<resourcePathName | !singularize | !uppercamelcase>> objects
