// DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
package types

import (
	"gopkg.in/validator.v2"
)

type Acl struct {
	Aci  []Aci  `json:"aci" validate:"nonzero"`
	Hash string `json:"hash" validate:"nonzero"`
	Uid  int32  `json:"uid" validate:"nonzero"`
}

func (s Acl) Validate() error {

	return validator.Validate(s)
}
