// DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
package types

import (
	"gopkg.in/validator.v2"
)

// blockchain domain
type Bdomain struct {
	Addr        string `json:"addr,omitempty"`
	Admins      int32  `json:"admins" validate:"nonzero"`
	Author      int32  `json:"author" validate:"nonzero"`
	Description string `json:"description,omitempty"`
	Id          int32  `json:"id" validate:"nonzero"`
	Moddate     int32  `json:"moddate" validate:"nonzero"`
	Name        string `json:"name" validate:"nonzero"`
	Signature   string `json:"signature" validate:"nonzero"`
	Uid         int32  `json:"uid" validate:"nonzero"`
}

func (s Bdomain) Validate() error {

	return validator.Validate(s)
}
