// DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
package types

import (
	"gopkg.in/validator.v2"
)

// blockchain object
type Bobject struct {
	Author          int32                      `json:"author" validate:"nonzero"`
	CompressionType EnumBobjectCompressionType `json:"compressionType,omitempty"`
	Data            string                     `json:"data" validate:"nonzero"`
	DigitalmeUrl    string                     `json:"digitalmeUrl,omitempty"`
	Domain          int32                      `json:"domain" validate:"nonzero"`
	Id              int32                      `json:"id" validate:"nonzero"`
	Key             string                     `json:"key" validate:"nonzero"`
	Moddate         int32                      `json:"moddate" validate:"nonzero"`
	Signature       string                     `json:"signature" validate:"nonzero"`
	Uid             int32                      `json:"uid,omitempty"`
}

func (s Bobject) Validate() error {

	return validator.Validate(s)
}
