// DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
package types

type EnumSpecialType string

const (
	EnumSpecialTypesocket EnumSpecialType = "socket"
	EnumSpecialTypeblock  EnumSpecialType = "block"
	EnumSpecialTypechar   EnumSpecialType = "char"
	EnumSpecialTypefifo   EnumSpecialType = "fifo"
)
