// DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
package types

type EnumLinkType string

const (
	EnumLinkTypefile EnumLinkType = "file"
	EnumLinkTypedir  EnumLinkType = "dir"
	EnumLinkTypemeta EnumLinkType = "meta"
)
