// DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
package types

type EnumBobjectCompressionType string

const (
	EnumBobjectCompressionTypenone   EnumBobjectCompressionType = "none"
	EnumBobjectCompressionTypeblosc  EnumBobjectCompressionType = "blosc"
	EnumBobjectCompressionTypesnappy EnumBobjectCompressionType = "snappy"
)
