// DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
package types

import (
	"gopkg.in/validator.v2"
)

type Fileblock struct {
	Hash          string `json:"hash,omitempty"`
	Key           string `json:"key,omitempty"`
	Zstormetadata string `json:"zstormetadata,omitempty"`
}

func (s Fileblock) Validate() error {

	return validator.Validate(s)
}
