// DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
package types

import (
	"gopkg.in/validator.v2"
)

type File struct {
	BlockSize int16  `json:"blockSize" validate:"nonzero"`
	Blocks    string `json:"blocks" validate:"nonzero"`
	Moddate   int32  `json:"moddate" validate:"nonzero"`
	Name      string `json:"name" validate:"nonzero"`
	Posix     string `json:"posix,omitempty"`
	Size      int32  `json:"size" validate:"nonzero"`
}

func (s File) Validate() error {

	return validator.Validate(s)
}
