// DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
package types

import (
	"gopkg.in/validator.v2"
)

type Link_bobject struct {
	Bdomain int32  `json:"bdomain" validate:"nonzero"`
	Buid    int32  `json:"buid" validate:"nonzero"`
	Moddate int32  `json:"moddate" validate:"nonzero"`
	Name    string `json:"name" validate:"nonzero"`
	Secret  string `json:"secret,omitempty"`
}

func (s Link_bobject) Validate() error {

	return validator.Validate(s)
}
