// DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
package types

import (
	"gopkg.in/validator.v2"
)

type Metadata struct {
	Category string `json:"category,omitempty"`
	Data     string `json:"data" validate:"nonzero"`
	Moddate  int32  `json:"moddate" validate:"nonzero"`
	Name     string `json:"name" validate:"nonzero"`
}

func (s Metadata) Validate() error {

	return validator.Validate(s)
}
