// DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
package types

import (
	"gopkg.in/validator.v2"
)

type Posix struct {
	Gname string `json:"gname" validate:"nonzero"`
	Mode  int16  `json:"mode,omitempty"`
	Uname string `json:"uname" validate:"nonzero"`
}

func (s Posix) Validate() error {

	return validator.Validate(s)
}
