// DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
package types

import (
	"gopkg.in/validator.v2"
)

type Special struct {
	Data    string          `json:"data,omitempty"`
	Moddate int32           `json:"moddate" validate:"nonzero"`
	Name    string          `json:"name" validate:"nonzero"`
	Type    EnumSpecialType `json:"type" validate:"nonzero"`
}

func (s Special) Validate() error {

	return validator.Validate(s)
}
