// DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
package client

import (
	"encoding/json"
	"net/http"

	"github.com/zero-os/0-metadata/go/client/goraml"
	"github.com/zero-os/0-metadata/go/client/types"
)

type AclService service

// Delete acl
func (s *AclService) DeleteAcl(id string, headers, queryParams map[string]interface{}) (*http.Response, error) {
	var err error

	resp, err := s.client.doReqNoBody("DELETE", s.client.BaseURI+"/acl/"+id, headers, queryParams)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	return resp, err
}

// Get acl, id=int
func (s *AclService) GetAcl(id string, headers, queryParams map[string]interface{}) (types.Acl, *http.Response, error) {
	var err error
	var respBody200 types.Acl

	resp, err := s.client.doReqNoBody("GET", s.client.BaseURI+"/acl/"+id, headers, queryParams)
	if err != nil {
		return respBody200, nil, err
	}
	defer resp.Body.Close()

	switch resp.StatusCode {
	case 200:
		err = json.NewDecoder(resp.Body).Decode(&respBody200)
	default:
		err = goraml.NewAPIError(resp, nil)
	}

	return respBody200, resp, err
}

// Update acl
func (s *AclService) UpdateAcl(id string, body types.Acl, headers, queryParams map[string]interface{}) (types.Acl, *http.Response, error) {
	var err error
	var respBody200 types.Acl

	resp, err := s.client.doReqWithBody("POST", s.client.BaseURI+"/acl/"+id, &body, headers, queryParams)
	if err != nil {
		return respBody200, nil, err
	}
	defer resp.Body.Close()

	switch resp.StatusCode {
	case 200:
		err = json.NewDecoder(resp.Body).Decode(&respBody200)
	default:
		err = goraml.NewAPIError(resp, nil)
	}

	return respBody200, resp, err
}

// Get a list of acls
func (s *AclService) ListAcl(headers, queryParams map[string]interface{}) ([]types.Acl, *http.Response, error) {
	var err error
	var respBody200 []types.Acl

	resp, err := s.client.doReqNoBody("GET", s.client.BaseURI+"/acl", headers, queryParams)
	if err != nil {
		return respBody200, nil, err
	}
	defer resp.Body.Close()

	switch resp.StatusCode {
	case 200:
		err = json.NewDecoder(resp.Body).Decode(&respBody200)
	default:
		err = goraml.NewAPIError(resp, nil)
	}

	return respBody200, resp, err
}
