// DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
package client

import (
	"encoding/json"
	"net/http"

	"github.com/zero-os/0-metadata/go/client/goraml"
	"github.com/zero-os/0-metadata/go/client/types"
)

type BobjectService service

// Delete bobject
func (s *BobjectService) DeleteBobject(id string, headers, queryParams map[string]interface{}) (*http.Response, error) {
	var err error

	resp, err := s.client.doReqNoBody("DELETE", s.client.BaseURI+"/bobject/"+id, headers, queryParams)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	return resp, err
}

// Get bobject, id=int
func (s *BobjectService) GetBobject(id string, headers, queryParams map[string]interface{}) (types.Bobject, *http.Response, error) {
	var err error
	var respBody200 types.Bobject

	resp, err := s.client.doReqNoBody("GET", s.client.BaseURI+"/bobject/"+id, headers, queryParams)
	if err != nil {
		return respBody200, nil, err
	}
	defer resp.Body.Close()

	switch resp.StatusCode {
	case 200:
		err = json.NewDecoder(resp.Body).Decode(&respBody200)
	default:
		err = goraml.NewAPIError(resp, nil)
	}

	return respBody200, resp, err
}

// Update bobject
func (s *BobjectService) UpdateBobject(id string, body types.Bobject, headers, queryParams map[string]interface{}) (types.Bobject, *http.Response, error) {
	var err error
	var respBody200 types.Bobject

	resp, err := s.client.doReqWithBody("POST", s.client.BaseURI+"/bobject/"+id, &body, headers, queryParams)
	if err != nil {
		return respBody200, nil, err
	}
	defer resp.Body.Close()

	switch resp.StatusCode {
	case 200:
		err = json.NewDecoder(resp.Body).Decode(&respBody200)
	default:
		err = goraml.NewAPIError(resp, nil)
	}

	return respBody200, resp, err
}

// Get a list of bobjects
func (s *BobjectService) ListBobject(headers, queryParams map[string]interface{}) ([]types.Bobject, *http.Response, error) {
	var err error
	var respBody200 []types.Bobject

	resp, err := s.client.doReqNoBody("GET", s.client.BaseURI+"/bobject", headers, queryParams)
	if err != nil {
		return respBody200, nil, err
	}
	defer resp.Body.Close()

	switch resp.StatusCode {
	case 200:
		err = json.NewDecoder(resp.Body).Decode(&respBody200)
	default:
		err = goraml.NewAPIError(resp, nil)
	}

	return respBody200, resp, err
}
