// DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
package client

import (
	"encoding/json"
	"net/http"

	"github.com/zero-os/0-metadata/go/client/goraml"
	"github.com/zero-os/0-metadata/go/client/types"
)

type DirService service

// Delete dir
func (s *DirService) DeleteDir(id string, headers, queryParams map[string]interface{}) (*http.Response, error) {
	var err error

	resp, err := s.client.doReqNoBody("DELETE", s.client.BaseURI+"/dir/"+id, headers, queryParams)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	return resp, err
}

// Get dir, id=int
func (s *DirService) GetDir(id string, headers, queryParams map[string]interface{}) (types.Dir, *http.Response, error) {
	var err error
	var respBody200 types.Dir

	resp, err := s.client.doReqNoBody("GET", s.client.BaseURI+"/dir/"+id, headers, queryParams)
	if err != nil {
		return respBody200, nil, err
	}
	defer resp.Body.Close()

	switch resp.StatusCode {
	case 200:
		err = json.NewDecoder(resp.Body).Decode(&respBody200)
	default:
		err = goraml.NewAPIError(resp, nil)
	}

	return respBody200, resp, err
}

// Update dir
func (s *DirService) UpdateDir(id string, body types.Dir, headers, queryParams map[string]interface{}) (types.Dir, *http.Response, error) {
	var err error
	var respBody200 types.Dir

	resp, err := s.client.doReqWithBody("POST", s.client.BaseURI+"/dir/"+id, &body, headers, queryParams)
	if err != nil {
		return respBody200, nil, err
	}
	defer resp.Body.Close()

	switch resp.StatusCode {
	case 200:
		err = json.NewDecoder(resp.Body).Decode(&respBody200)
	default:
		err = goraml.NewAPIError(resp, nil)
	}

	return respBody200, resp, err
}

// Get a list of dirs
func (s *DirService) ListDir(headers, queryParams map[string]interface{}) ([]types.Dir, *http.Response, error) {
	var err error
	var respBody200 []types.Dir

	resp, err := s.client.doReqNoBody("GET", s.client.BaseURI+"/dir", headers, queryParams)
	if err != nil {
		return respBody200, nil, err
	}
	defer resp.Body.Close()

	switch resp.StatusCode {
	case 200:
		err = json.NewDecoder(resp.Body).Decode(&respBody200)
	default:
		err = goraml.NewAPIError(resp, nil)
	}

	return respBody200, resp, err
}
