# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

from flask import Flask, send_from_directory, send_file
try:
    from .acl_api import acl_api
    from .bdomain_api import bdomain_api
    from .bobject_api import bobject_api
    from .dir_api import dir_api
    from .group_api import group_api
    from .user_api import user_api
except:
    from acl_api import acl_api
    from bdomain_api import bdomain_api
    from bobject_api import bobject_api
    from dir_api import dir_api
    from group_api import group_api
    from user_api import user_api


import os
dir_path = os.path.dirname(os.path.realpath(__file__))

app = Flask(__name__)

app.register_blueprint(acl_api)
app.register_blueprint(bdomain_api)
app.register_blueprint(bobject_api)
app.register_blueprint(dir_api)
app.register_blueprint(group_api)
app.register_blueprint(user_api)


@app.route('/apidocs/<path:path>')
def send_js(path):
    return send_from_directory(dir_path + '/' + 'apidocs', path)


@app.route('/', methods=['GET'])
def home():
    return send_file(dir_path + '/index.html')


if __name__ == "__main__":
    app.run(debug=True)
