# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

from flask import Blueprint
try:
    import handlers
except ImportError:
    from . import handlers


bdomain_api = Blueprint('bdomain_api', __name__)


@bdomain_api.route('/bdomain', methods=['GET'])
def listBdomain():
    """
    Get a list of bdomains
    It is handler for GET /bdomain
    """
    return handlers.listBdomainHandler()


@bdomain_api.route('/bdomain/<id>', methods=['GET'])
def getBdomain(id):
    """
    Get bdomain, id=int
    It is handler for GET /bdomain/<id>
    """
    return handlers.getBdomainHandler(id)


@bdomain_api.route('/bdomain/<id>', methods=['POST'])
def updateBdomain(id):
    """
    Update bdomain
    It is handler for POST /bdomain/<id>
    """
    return handlers.updateBdomainHandler(id)


@bdomain_api.route('/bdomain/<id>', methods=['DELETE'])
def deleteBdomain(id):
    """
    Delete bdomain
    It is handler for DELETE /bdomain/<id>
    """
    return handlers.deleteBdomainHandler(id)
