# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

from flask import Blueprint
import handlers


bobject_api = Blueprint('bobject_api', __name__)


@bobject_api.route('/bobject', methods=['GET'])
def listBobject():
    """
    Get a list of bobjects
    It is handler for GET /bobject
    """
    return handlers.listBobjectHandler()


@bobject_api.route('/bobject/<id>', methods=['GET'])
def getBobject(id):
    """
    Get bobject, id=int
    It is handler for GET /bobject/<id>
    """
    return handlers.getBobjectHandler(id)


@bobject_api.route('/bobject/<id>', methods=['POST'])
def updateBobject(id):
    """
    Update bobject
    It is handler for POST /bobject/<id>
    """
    return handlers.updateBobjectHandler(id)


@bobject_api.route('/bobject/<id>', methods=['DELETE'])
def deleteBobject(id):
    """
    Delete bobject
    It is handler for DELETE /bobject/<id>
    """
    return handlers.deleteBobjectHandler(id)
