# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

from flask import Blueprint
try:
    import handlers
except ImportError:
    from . import handlers


dir_api = Blueprint('dir_api', __name__)


@dir_api.route('/dir', methods=['GET'])
def listDir():
    """
    Get a list of dirs
    It is handler for GET /dir
    """
    return handlers.listDirHandler()


@dir_api.route('/dir/<id>', methods=['GET'])
def getDir(id):
    """
    Get dir, id=int
    It is handler for GET /dir/<id>
    """
    return handlers.getDirHandler(id)


@dir_api.route('/dir/<id>', methods=['POST'])
def updateDir(id):
    """
    Update dir
    It is handler for POST /dir/<id>
    """
    return handlers.updateDirHandler(id)


@dir_api.route('/dir/<id>', methods=['DELETE'])
def deleteDir(id):
    """
    Delete dir
    It is handler for DELETE /dir/<id>
    """
    return handlers.deleteDirHandler(id)
