# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

from flask import Blueprint
try:
    import handlers
except ImportError:
    from . import handlers


user_api = Blueprint('user_api', __name__)


@user_api.route('/user', methods=['GET'])
def listUser():
    """
    Get a list of users
    It is handler for GET /user
    """
    return handlers.listUserHandler()


@user_api.route('/user/<id>', methods=['GET'])
def getUser(id):
    """
    Get user, id=int
    It is handler for GET /user/<id>
    """
    return handlers.getUserHandler(id)


@user_api.route('/user/<id>', methods=['POST'])
def updateUser(id):
    """
    Update user
    It is handler for POST /user/<id>
    """
    return handlers.updateUserHandler(id)


@user_api.route('/user/<id>', methods=['DELETE'])
def deleteUser(id):
    """
    Delete user
    It is handler for DELETE /user/<id>
    """
    return handlers.deleteUserHandler(id)
