# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
@0xa93f51dc0c99b97a;

struct Aci {
  groups @0 :Int32;
  hash @1 :Text;
  right @2 :Text;
  uid @3 :Int32;
  users @4 :Int32;
}
