# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
using import "EnumBobjectCompressionType.capnp".EnumBobjectCompressionType;
@0xbe9701a374696d34;

struct Bobject {
  author @0 :UInt32;
  compressionType @1 :EnumBobjectCompressionType;
  data @2 :Text;
  domain @3 :UInt32;
  id @4 :UInt32;
  key @5 :Text;
  moddate @6 :UInt32;
  signature @7 :Text;
  uid @8 :UInt32;
}
