# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
@0xa7b7cf4de995781c;

struct LinkBobject {
  bdomain @0 :UInt32;
  buid @1 :UInt32;
  moddate @2 :UInt32;
  name @3 :Text;
  secret @4 :Text;
}
