# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
using import "EnumLinkType.capnp".EnumLinkType;
@0xa2db95422b60adff;

struct Link {
  destdir @0 :UInt32;
  destname @1 :UInt32;
  moddate @2 :UInt32;
  name @3 :Text;
  type @4 :EnumLinkType;
}
